---

- name: Download and unarchive Nagios Plugins
  unarchive:
    src: "{{ pluginsurl }}"
    dest: "{{ download_dir }}"
    remote_src: true

- name: Configure
  command:
    cmd: ./configure --with-nagios-user={{ monitoring_user }} --with-nagios-group=nagios --with-openssl=/usr/bin/openssl
    chdir: "{{ download_dir }}/{{ pluginsrc }}"
    creates: "{{ download_dir }}/{{ pluginsrc }}/Makefile"

- name: Make Plugins
  make:
    chdir: "{{ download_dir }}/{{ pluginsrc }}"
    target: default
    params:
      NUM_THREADS: 4
#  creates: "{{ download_dir }}/{{ pluginsrc }}/plugins/check_ping"

- name: Make Install Plugins
  make:
    chdir: "{{ download_dir }}/{{ pluginsrc }}"
    target: install
#  creates: /usr/local/nagios/libexec/check_ping
